name: build_daemon 
version: 0.0.1
description: A daemon for running Dart builds. 
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/build/tree/master/build_daemon

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  built_collection: ^4.1.0
  built_value: ^6.2.0
  pedantic: ^1.0.0
  watcher: ^0.9.7


dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^6.2.0
  mockito: ^4.0.0
  test: ^1.3.3
  test_descriptor: ^1.1.1
  uuid: ^1.0.3
